version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    reviewers:
      - "hassanazam"
    commit-message:
      prefix: "🔒"
      include: "scope"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    reviewers:
      - "hassanazam"
    commit-message:
      prefix: "🔒"
      include: "scope"