name: Test Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  test-pr:
    runs-on: ubuntu-latest
    
    env:
      PYTHONIOENCODING: utf-8
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install and test
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    
    - name: Test basic functionality
      run: |
        python -c "import claude_cost; print('Package imports successfully')"
        claude-cost --help
        echo "Basic tests passed"
    
    - name: Privacy compliance check
      run: |
        echo "🔒 Checking for privacy compliance..."
        ! grep -r "\.content\|message.*text\|data\[.*content\]" src/claude_cost/ --include="*.py" || {
          echo "❌ Found potential content access in code"
          exit 1
        }
        echo "✅ Privacy compliance verified - no content access found"